name: Frontend CI

on:
  push:
    paths:
    - '.github/workflows/**'
    - 'frontend/**'
  pull_request:
    paths:
    - '.github/workflows/**'
    - 'frontend/**'

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm ci
    - name: Lint frontend codebase
      run: npm run lint
    - name: Build frontend
      run: npm run build
    - name: Publish on Netlify
      uses: netlify/actions/build@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_BASE: frontend
        NETLIFY_CMD: npm build
        NETLIFY_DIR: frontend/build
