name: Frontend CI

on:
  push:
    branches:
      - master
    paths:
    - '.github/workflows/frontend.yml'
    - 'frontend/**'
  pull_request:
    branches:
      - master
    paths:
    - '.github/workflows/frontend.yml'
    - 'frontend/**'

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm ci
    - name: Lint frontend codebase
      run: npm run lint
    - name: Build frontend
      run: npm run build
      env:
        REACT_APP_BACKEND_API: ${{ secrets.APP_BACKEND_API }}
    - name: Publish on Netlify
      uses: nwtgck/actions-netlify@v1.1
      with:
        publish-dir: './frontend/build'
        production-branch: master
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: false
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1
